### ISSUE TITLE
Unas cosas.

### ISSUE THREAD

**Issue by darkxex** [Manurocker95/Anim3DS#2]
Hola man, detendré el proyecto mío, así me dedico a otra cosa.
lo otro es que para el buscador.

la primera condición es que la variable sea mayor a 3, por ende ve si puedes agregar un mensaje con un if, ejemplo.
1.  https://animeflv.net/browse?q=fai
(Debe ingresar 4 o más caracteres.)
https://animeflv.net/browse?q=fair ahí sería correcto.

lo segundo, el buscador arroja la primera serie que encuentra. ejemplo si buscas  One P
te tira a one piece, pero también hay otras series como One Punch o en el mismo caso de fairy tail que tiene ambas temporadas siempre te tirará a la primera.

lo que yo hice en android para esto, RipEX es una app de android  https://github.com/darkxex/Rip/releases/download/66/ripexa66.apk
como te decía lo que yo hice en esto, fue hacer una tercera vista.  ejemplo en la primera vista está el buscador, y en vez de que te lance a la serie más cercana, usa un while para extraer todos los url de series con esos terminos, los muestran en pantalla, el usuario escoge que serie quiere ver, presiona, y ahí extraes la lista de episodios. eso sería man, suerte con el proyecto.

**Comment by Manurocker95** [comment]
Lo que he hecho es que te coja el primer anime que encuentra en la búsqueda. Supongo que todo el que busque por nombre lo hará poniendo algo aproximado a lo que quiere. 

Anim3DS está inspirado en tu ripEx3DS, así que eres bienvenido a probarlo y por supuesto todas las sugerencias y ayudas son bienvenidas.

**Comment by darkxex** [comment]
es que a eso iba, animeflv tiene un bug que si ingresas el nombre de la serie completa, a veces el buscador no te mostrará la serie, por eso usas una palabra, y para solucionar eso, es lo que te dije, dar soporte a la lista completa.
