### ISSUE TITLE
Will there ever be an english version?

### ISSUE THREAD

**Issue by TildeEthDoUsPart** [Manurocker95/Anim3DS#3]
As the title said: Will there ever be an english version? Or maybe a translation project? I'd like to add my contribution, but I can't find the right files to edit.

**Comment by apes0** [comment]
I hope there would be, but it seems that this project is dead, as are most projects :(

**Comment by LittleTale** [comment]
There will never be an english version as this project is mainly an app to view a popular spanish based anime rip website called AnimeFLV directly on your 3DS ! ! ! So they cannot magically add english dub and sub cause they don't exist on this website !

**Comment by TildeEthDoUsPart** [comment]
Oh, alright, I see. Thanks for the answer!
